name: aliyundrive_sign_bot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '15 0 * * *'
      env:
        TZ: Asia/Shanghai # 设置时区为上海（+8）
  watch:
    types: started

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: 安装环境
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 阿里云盘签到
      run: |
        refresh_token='${{ secrets.ALIYUNDRIVE_REFRESH_TOKEN }}'
        python aliyundrive_sign.py <<EOF
        ${refresh_token}
        EOF
