name: aliyundrive_sign_bot

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: "55 15 * * *"
    - cron: "0 */8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: 安装环境
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 阿里云盘签到
      env:
        PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
      run: |
        refresh_token='${{ secrets.ALIYUNDRIVE_REFRESH_TOKEN }}'
        python aliyundrive_sign.py <<EOF
        ${refresh_token}
        EOF
