name: iopq_sign_bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # 手动触发
  schedule:
    - cron: "2 16 * * *" # 每天16点执行一次
    - cron: "0 */6 * * *" # 每6小时执行一次

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: 安装环境
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: iopq签到
      env:
        PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
      run: |
        cookie='${{ secrets.IOPQ_COOKIE }}'
        python iopq_sign.py <<EOF
        ${cookie}
        EOF
